# Generated by Django 5.2 on 2025-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_anime_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
