# Generated by Django 5.2 on 2025-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Виділити як нову'),
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='Теги'),
        ),
    ]
