# Generated by Django 5.2 on 2025-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аніме', 'verbose_name_plural': 'Аніме'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(verbose_name='Кількість епізодів'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='catalog.genre', verbose_name='Жанри'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime/%Y/%m/%d/', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Перегляди'),
        ),
    ]
