# Generated by Django 5.2 on 2025-06-12 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_anime_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
