# Generated by Django 5.2 on 2025-06-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_anime_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата виходу'),
        ),
    ]
