# Generated by Django 5.2 on 2025-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_anime_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.CharField(blank=True, choices=[('live', 'Live Action'), ('trending', 'Trending Now'), ('popular', 'Popular Shows'), ('recent', 'Recently Added Shows')], help_text='Категорія для секцій головної сторінки', max_length=20, null=True, verbose_name='Категорія для головної'),
        ),
    ]
