# Generated by Django 5.2 on 2025-06-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_anime_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.anime')),
            ],
            options={
                'verbose_name': 'Герой-слайд',
                'verbose_name_plural': 'Герой-слайди',
                'ordering': ['order'],
            },
        ),
    ]
