# Generated by Django 5.2 on 2025-06-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_author_newsarticle_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Зображення (фон)'),
        ),
    ]
