# Generated by Django 5.2 on 2025-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author_blogpost_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Чорнетка'), ('published', 'Опубліковано')], default='draft', max_length=10),
        ),
    ]
